# Generated by Django 4.2.2 on 2023-06-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reffrences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('instruction', models.TextField()),
                ('reference_image', models.ImageField(upload_to='reference_images/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
