# Generated by Django 4.2.2 on 2023-06-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reffrences',
            old_name='instruction',
            new_name='aciklama',
        ),
        migrations.RenameField(
            model_name='reffrences',
            old_name='title',
            new_name='baslik',
        ),
        migrations.RenameField(
            model_name='reffrences',
            old_name='reference_image',
            new_name='referans_fotografi',
        ),
    ]
