# Generated by Django 4.1.7 on 2023-07-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_instruction_reffrences_aciklama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reffrences',
            name='referans_fotografi',
            field=models.ImageField(upload_to='reference_images/% Y/% m/% d/'),
        ),
    ]
