# Generated by Django 4.1.7 on 2023-07-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_reffrences_referans_fotografi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reffrences',
            options={'verbose_name': 'Referans Yonetimi', 'verbose_name_plural': 'Referans Yonetimi'},
        ),
    ]
