# Generated by Django 4.1.7 on 2023-07-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_reffrences_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reffrences',
            name='kategori',
            field=models.CharField(choices=[['Yol ve Köprü İnşaatı ', 'Yol ve Köprü İnşaatı'], ['Binalar', 'Binalar'], ['Bakım ve Onarım', 'Bakım ve Onarım'], ['Tesisat İnşaatı', 'Tesisat İnşaatı']], default='Bir Kategori Seçiniz.', max_length=50),
        ),
    ]
