# Generated by Django 4.1.7 on 2023-07-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reffrences_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reffrences',
            name='kategori',
            field=models.CharField(choices=[['Yol ve Köprü İnşaatı', 'Yol ve Köprü İnşaatı'], ['Binalar', 'Binalar'], ['Bakım ve Onarım', 'Bakım ve Onarım'], ['Tesisat İnşaatı', 'Tesisat İnşaatı']], default='Yol ve Köprü İnşaatı', max_length=50),
        ),
        migrations.AlterField(
            model_name='reffrences',
            name='referans_fotografi',
            field=models.ImageField(upload_to='media/reference_images/'),
        ),
    ]
