# Generated by Django 4.1.7 on 2024-01-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_reffrences_kategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reffrences',
            name='kategori',
        ),
        migrations.AddField(
            model_name='reffrences',
            name='referans_dosyasi',
            field=models.FileField(default='some string', upload_to='media/reference_file/'),
        ),
    ]
