# Generated by Django 4.1.7 on 2024-01-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_reffrences_kategori_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefrrenceProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proje', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='reffrences',
            name='baslik',
        ),
        migrations.RemoveField(
            model_name='reffrences',
            name='referans_dosyasi',
        ),
        migrations.AddField(
            model_name='reffrences',
            name='proje',
            field=models.ManyToManyField(to='api.refrrenceproject'),
        ),
    ]
