# Generated by Django 4.1.7 on 2024-01-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_refrrenceproject_remove_reffrences_baslik_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reffrences',
            name='proje',
        ),
        migrations.AddField(
            model_name='reffrences',
            name='baslik',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='reffrences',
            name='aciklama',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='RefrrenceProject',
        ),
    ]
