# Generated by Django 4.1.7 on 2024-01-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_reffrences_proje_reffrences_baslik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reffrences',
            name='baslik',
            field=models.CharField(max_length=150),
        ),
    ]
