# Generated by Django 4.1.7 on 2024-01-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_reffrences_baslik'),
    ]

    operations = [
        migrations.AddField(
            model_name='reffrences',
            name='referans_fotografi_10',
            field=models.ImageField(default='', upload_to='media/reference_images/'),
        ),
        migrations.AddField(
            model_name='reffrences',
            name='referans_fotografi_2',
            field=models.ImageField(default='', upload_to='media/reference_images/'),
        ),
        migrations.AddField(
            model_name='reffrences',
            name='referans_fotografi_3',
            field=models.ImageField(default='', upload_to='media/reference_images/'),
        ),
        migrations.AddField(
            model_name='reffrences',
            name='referans_fotografi_4',
            field=models.ImageField(default='', upload_to='media/reference_images/'),
        ),
        migrations.AddField(
            model_name='reffrences',
            name='referans_fotografi_5',
            field=models.ImageField(default='', upload_to='media/reference_images/'),
        ),
        migrations.AddField(
            model_name='reffrences',
            name='referans_fotografi_6',
            field=models.ImageField(default='', upload_to='media/reference_images/'),
        ),
        migrations.AddField(
            model_name='reffrences',
            name='referans_fotografi_7',
            field=models.ImageField(default='', upload_to='media/reference_images/'),
        ),
        migrations.AddField(
            model_name='reffrences',
            name='referans_fotografi_8',
            field=models.ImageField(default='', upload_to='media/reference_images/'),
        ),
        migrations.AddField(
            model_name='reffrences',
            name='referans_fotografi_9',
            field=models.ImageField(default='', upload_to='media/reference_images/'),
        ),
        migrations.AlterField(
            model_name='reffrences',
            name='referans_fotografi',
            field=models.ImageField(default='', upload_to='media/reference_images/'),
        ),
    ]
