# Generated by Django 4.1.7 on 2024-01-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_reffrences_referans_fotografi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reffrences',
            old_name='referans_fotografi',
            new_name='referans_fotografi_1',
        ),
    ]
